### ISSUE TITLE
fix: 영상 보관시 이전에 보관한 영상이 보관해제되는 버그

### ISSUE THREAD

**Issue by Yeonwu** [EO2-WAVY/WavyBackend#107]

**Comment by Yeonwu** [comment]
bookmark.service.ts 142줄
`member.bookmarkedRefVideos = [refVideo];`
이때 member.bookmarkedRefVideos를 못 불러온 상태에서 할당을 해서 이전 데이터가 덮어씌워지는 듯 합니다.

**Comment by haeseoklee** [comment]
@Yeonwu 
typeorm의 ManyToMany 관계를 커스텀으로 정의해줬는데 요게 무슨 문제 때문인지 저장시 잘 작동하지 않더라구요 
다행이도 현재는 다른 방법으로 해결완료했습니다
