### ISSUE TITLE
feat: CORS 해결

### ISSUE THREAD

**Issue by Yeonwu** [EO2-WAVY/WavyBackend#67]
- localhost:3000, wavy.dance

**Comment by Yeonwu** [comment]
https://docs.nestjs.com/security/cors

**Comment by hyesungoh** [comment]
현재 배포 상태가 502를 뱉습니다 ㅠ 확인 부탁드립니다

**Comment by Yeonwu** [comment]
@hyesungoh 
알겠습니다! 확인해보고 알려드리겠습니다

**Comment by Yeonwu** [comment]
@hyesungoh 
502에러 고쳤습니다!
