### ISSUE TITLE
fix: Auth 토큰 받아오지 못함

### ISSUE THREAD

**Issue by Yeonwu** [EO2-WAVY/WavyBackend#71]

**Comment by hyesungoh** [comment]
### 문제 정의

로그아웃 후, 재 로그인 시도할 시 `/member/signup`에서 발급되는 최종 토큰을 받아오지 못하여 모든 접근이 불가합니다.

### 문제 상황

1. 로그인 
2. `클라이언트/auth/kakaoLoginRedirect` 에서 `1차` 토큰 발급 
3. `1차` 토큰을 이용해 `서버/auth/token` 에 요청하여 2차 `서버 토큰`을 저장 
4. `서버 토큰`을 이용해 `/members/me` 호출하여 회원가입 여부 판별
5.  하지만 `서버 토큰`은 최종적으로 사용가능한 `회원가입 시 반환하는 토큰`이 아님
6.  무한 회원가입
