### ISSUE TITLE
fix: ref-video 인터페이스 통일

### ISSUE THREAD

**Issue by hyesungoh** [EO2-WAVY/WavyBackend#83]
### 문제

현재 `/ref-videos`에서 반환하는 `학습용 영상`과

`/ref-videos/search`에서 반환하는 `학습용 영상`의 `난이도 부분` 인터페이스가 다릅니다.

`rvDifficultyCd` 혹은 `rvDifficulty` 둘 중 하나로 통일 부탁드립니다.

#### /ref-videos

![스크린샷 2021-10-08 오전 12 09 36](https://user-images.githubusercontent.com/26461307/136412574-df9713b1-aa2e-4d36-85de-1aeac9dcffe3.png)

#### /ref-videos/search

![스크린샷 2021-10-08 오전 12 11 39](https://user-images.githubusercontent.com/26461307/136412929-f5591e50-5255-4da0-a893-330f2250b238.png)

**Comment by haeseoklee** [comment]
@hyesungoh  refDifficultyCd 로 통일하겠습니다
